### ISSUE TITLE
REgression in version 2.0.2

### ISSUE THREAD

**Issue by F242MX** [CycloneDX/cyclonedx-node-module#117]
I observe a regression in the version 2.0.2, this happens:

cyclonedx-bom -h
/usr/lib/node_modules/@cyclonedx/bom/node_modules/ssri/index.js:25
const ssriOpts = (opts = {}) => ({ ...defaultOpts, ...opts })
                                   ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/@cyclonedx/bom/model/HashList.js:19:14)

Note : the program behaves normally in version 2.0.1

**Comment by jkowalleck** [comment]
@F242MX is this still an issue in current v3 ?
