### ISSUE TITLE
Cannot read property 'integrity' of undefined

### ISSUE THREAD

**Issue by RussellLMiller** [CycloneDX/cyclonedx-node-module#169]
Noticed this issue on my pipelines this morning when running `cyclonedx-bom -d -o test_bom.json`. 

It worked when I reverted back to version 3.0.4 or when I didn't include devDependencies. 

Would like to stay on the most current version when running this tool and include my devDependencies

Are you aware of this issue and other than my work-arounds above do you have any suggestions?

Stack Trace
```
.\AppData\Roaming\npm\node_modules\@cyclonedx\bom\model\HashList.js:48
      if (lockfile.dependencies[pkg.name].integrity) {
                                          ^

TypeError: Cannot read property 'integrity' of undefined
    at HashList.processHashes (.\AppData\Roaming\npm\node_modules\@cyclonedx\bom\model\HashList.js:48:43)
    at new HashList (.\AppData\Roaming\npm\node_modules\@cyclonedx\bom\model\HashList.js:27:12)
    at new Component (.\AppData\Roaming\npm\node_modules\@cyclonedx\bom\model\Component.js:41:22)
    at Bom.createComponent (.\AppData\Roaming\npm\node_modules\@cyclonedx\bom\model\Bom.js:75:23)
    at .\AppData\Roaming\npm\node_modules\@cyclonedx\bom\model\Bom.js:86:24
    at Array.map (<anonymous>)
    at Bom.createComponent (.\AppData\Roaming\npm\node_modules\@cyclonedx\bom\model\Bom.js:86:10)
    at .\AppData\Roaming\npm\node_modules\@cyclonedx\bom\model\Bom.js:86:24
    at Array.map (<anonymous>)
    at Bom.createComponent (.\AppData\Roaming\npm\node_modules\@cyclonedx\bom\model\Bom.js:86:10)
```

**Comment by stevespringett** [comment]
v3.0.5 was this issue. However, v3.0.6 was released earlier today which may solve this. Can you confirm what version you're using?

**Comment by kuzirh** [comment]
Hello I can confirm that this issue persists on 3.0.6

**Comment by stevespringett** [comment]
v3.0.7 should now resolve it.
