### ISSUE TITLE
FF in license file throws error

### ISSUE THREAD

**Issue by CompartMSL** [CycloneDX/cyclonedx-node-module#255]
After calling
`npx @cyclonedx/bom -l`
I got a 
`throw new Error("Invalid character in string: ${str} at index ${res.index}");`

It happens only with the parameter -l for "Include full license text"

Add the mentioned position is a form feed (0x0c) in the text. I guess, that the form feed is not correctly handled/masked/.. for the xml output.

The simplified used package.json is
`{
  "name": "bom_formfeed_in_license_file_issue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "author": "CompartMSL",
  "license": "ISC",
  "dependencies": {
    "mariadb": "^2.5.5"
  }
}`

Stdout/stderr in more details
```
            throw new Error(`Invalid character in string: ${str} at index ${res.index}`);
            ^

Error: Invalid character in string:                  GNU LESSER GENERAL PUBLIC LICENSE
                       Version 2.1, February 1999

 Copyright (C) 1991, 1999 Free Software Foundation, Inc.
[..]
That's all there is to it!
 at index undefined
    at XMLStringifier.assertLegalChar (C:\Users\msl\AppData\Roaming\npm-cache\_npx\16684\node_modules\@cyclonedx\bom\node_modules\xmlbuilder\lib\XMLStringifier.js:210:19)
    at XMLStringifier.cdata (C:\Users\msl\AppData\Roaming\npm-cache\_npx\16684\node_modules\@cyclonedx\bom\node_modules\xmlbuilder\lib\XMLStringifier.js:62:21)
    at new XMLCData (C:\Users\msl\AppData\Roaming\npm-cache\_npx\16684\node_modules\@cyclonedx\bom\node_modules\xmlbuilder\lib\XMLCData.js:21:35)
    at XMLElement.cdata (C:\Users\msl\AppData\Roaming\npm-cache\_npx\16684\node_modules\@cyclonedx\bom\node_modules\xmlbuilder\lib\XMLNode.js:318:17)
    at XMLElement.element (C:\Users\msl\AppData\Roaming\npm-cache\_npx\16684\node_modules\@cyclonedx\bom\node_modules\xmlbuilder\lib\XMLNode.js:175:30)
    at XMLElement.element (C:\Users\msl\AppData\Roaming\npm-cache\_npx\16684\node_modules\@cyclonedx\bom\node_modules\xmlbuilder\lib\XMLNode.js:163:32)
    at XMLElement.element (C:\Users\msl\AppData\Roaming\npm-cache\_npx\16684\node_modules\@cyclonedx\bom\node_modules\xmlbuilder\lib\XMLNode.js:158:27)
    at XMLElement.element (C:\Users\msl\AppData\Roaming\npm-cache\_npx\16684\node_modules\@cyclonedx\bom\node_modules\xmlbuilder\lib\XMLNode.js:158:27)
    at XMLElement.element (C:\Users\msl\AppData\Roaming\npm-cache\_npx\16684\node_modules\@cyclonedx\bom\node_modules\xmlbuilder\lib\XMLNode.js:115:30)
    at XMLElement.element (C:\Users\msl\AppData\Roaming\npm-cache\_npx\16684\node_modules\@cyclonedx\bom\node_modules\xmlbuilder\lib\XMLNode.js:158:27)```

**Comment by jkowalleck** [comment]
Thanks for the report @CompartMSL ,

could you setup a repository that showcases the issue? 
OR create a pullrequest with a test for that, like the integration tests here: https://github.com/CycloneDX/cyclonedx-node-module/blob/master/tests/index.test.js ?

**Comment by jkowalleck** [comment]
The issue could be caused upstream from https://www.npmjs.com/package/xmlbuilder
please report it there, and link it to this very issue here.

Thanks in advance, @CompartMSL

**Comment by CompartMSL** [comment]
Created pull request https://github.com/CycloneDX/cyclonedx-node-module/pull/257
