### ISSUE TITLE
Invalid or unexpected token in 3.4.1

### ISSUE THREAD

**Issue by rkg-mm** [CycloneDX/cyclonedx-node-module#256]
New version seems to be broken:
> npx @cyclonedx/bom my\path --include-license-text --output "my\path\bom.xml" --type application
npx: installed 47 in 4.703s
Invalid or unexpected token

After forcing old version it works fine:
> npx @cyclonedx/bom@3.3.1 my\path --include-license-text --output "my\path\bom.xml" --type application

Unfortunately, there is no more output that could help track this down :/

version 3.4.0 also has the same issue.

**Comment by jkowalleck** [comment]
Thanks for the report @rstmm  ,

could you setup a repository that showcases the issue? 
OR create a pullrequest with a test for that, like the integration tests here: https://github.com/CycloneDX/cyclonedx-node-module/blob/master/tests/index.test.js ?

**Comment by danchik1155** [comment]
Log from my console
`root@d34177585821:/app# npm install -g @cyclonedx/bom@3.9.0
/usr/local/bin/cyclonedx-bom -> /usr/local/lib/node_modules/@cyclonedx/bom/bin/make-bom.js
/usr/local/bin/cyclonedx-node -> /usr/local/lib/node_modules/@cyclonedx/bom/bin/make-bom.js
npm WARN notsup Unsupported engine for @cyclonedx/bom@3.9.0: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @cyclonedx/bom@3.9.0
npm WARN notsup Unsupported engine for commander@8.3.0: wanted: {"node":">= 12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: commander@8.3.0

+ @cyclonedx/bom@3.9.0
added 76 packages from 51 contributors in 7.429s
root@d34177585821:/app# cyclonedx-node -o /dow/bom.xml
/usr/local/lib/node_modules/@cyclonedx/bom/model/Component.js:50
  #type = 'library'
  ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@cyclonedx/bom/model/Bom.js:22:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
root@d34177585821:/app# 

`
