### ISSUE TITLE
Failed to generate BOM file

### ISSUE THREAD

**Issue by phoenixadb** [CycloneDX/cyclonedx-node-module#40]
Hello,

I tried to generate a BOM file but it raises an error :

cyclonedx-bom -o bom.xml
/usr/local/lib/node_modules/@cyclonedx/bom/bin/cyclonedx-bom:10
let arguments = process.argv.slice(2);
                                    ^
SyntaxError: Identifier 'arguments' has already been declared
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by stevespringett** [comment]
Unable to replicate using Node v10.16.0.

**Comment by phoenixadb** [comment]
Hi @stevespringett ,

I used node v6.9.2. Do you have requierements about minimal node version?

**Comment by phoenixadb** [comment]
It works with  v13.6.0.

**Comment by stevespringett** [comment]
Node 8.0.0 or higher is required. This is stated in the package.json https://github.com/CycloneDX/cyclonedx-node-module/blob/master/package.json#L39 but should ideally be mentioned in the readme as well.

**Comment by stevespringett** [comment]
Closing
