### ISSUE TITLE
Error: cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Drewster727** [CycloneDX/cyclonedx-node-module#5]
@cyclonedx/bom@0.2.4
npm v5.4.2
node v8.9.3

Running this command:
`cyclonedx-bom -o . <path>`

Seeing this error:
```C:\Users\user1\AppData\Roaming\npm\node_modules\@cyclonedx\bom\index.js:46
    let purlName = pkg.name.replace("@", "%40"); // Encode 'scoped' npm packages in purl
                            ^

TypeError: Cannot read property 'replace' of undefined
    at addComponent (C:\Users\user1\AppData\Roaming\npm\node_modules\@cyclonedx\bom\index.js:46:29)
    at listComponents (C:\Users\user1\AppData\Roaming\npm\node_modules\@cyclonedx\bom\index.js:35:5)
    at readInstalled (C:\Users\user1\AppData\Roaming\npm\node_modules\@cyclonedx\bom\index.js:159:15)
    at C:\Users\user1\AppData\Roaming\npm\node_modules\@cyclonedx\bom\node_modules\read-installed\read-installed.js:142:5
    at C:\Users\user1\AppData\Roaming\npm\node_modules\@cyclonedx\bom\node_modules\read-installed\read-installed.js:263:14
    at asyncMap (C:\Users\user1\AppData\Roaming\npm\node_modules\@cyclonedx\bom\node_modules\slide\lib\async-map.js:27:18)
    at next (C:\Users\user1\AppData\Roaming\npm\node_modules\@cyclonedx\bom\node_modules\read-installed\read-installed.js:234:5)
    at C:\Users\user1\AppData\Roaming\npm\node_modules\@cyclonedx\bom\node_modules\read-installed\read-installed.js:179:7
    at LOOP (fs.js:1745:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

**Comment by Drewster727** [comment]
I think the following line is the culprit. It attempts to read properties from an empty list.
https://github.com/CycloneDX/cyclonedx-node-module/blob/70eab8ee09255bc95cd96f206599257ba1c1292b/index.js#L35

**Comment by Drewster727** [comment]
yeah, so for some reason pkg.name is not available:
https://github.com/CycloneDX/cyclonedx-node-module/blob/1cd781179cab7bc1739bafd76bfa61aec1e9917b/index.js#L46

**Comment by Drewster727** [comment]
Hmm -- well I don't know where to go from here. Can we not continue the scan and send that to a log or debug/error output?

**Comment by Drewster727** [comment]
OK -- this may be a bug or a misunderstanding on my part.

I have a project structured like so:
```
project-root\
|--web\ (contains my package.json)
|--api\
|--dataaccess\
|--businesslogic\
|--etc\
```
When I run: `cyclonedx-bom` on the project-root folder it blows up.
When I run: `cyclonedx-bom project-root\web` it works.

So I'm assuming it is finding package.json and working from there. I thought I could give it a parent folder and it would recursively search for package.json files...

My apologies if this is my misunderstanding.
